### ISSUE TITLE
Is there a way to make it so that you can import a drop table from loot tracker?

### ISSUE THREAD

**Issue by BestMod** [ThePharros/probability-calculator#6]
So like you can rclick a tab in loot tracker maybe, then it would calculate the probability of all of the drops.

**Comment by ThePharros** [comment]
Another user had the suggestion (#4) of manually choosing an enemy and drop for the plugin to dynamically calculate the probabilities, however, this does seem like a more convenient behavior. Unfortunately that would require custom code on top of the loot tracker, which is not something that can be done without replacing the vanilla loot tracker behavior, which that itself is not something I'd be willing to have the third party plugin do. I may however look into the aforementioned approach of manually choosing which monster and item to track.

Closing as this is not something the plugin can do without creating other issues, and the other suggestion may be the more feasible alternative in that case.
